/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pontocerto.Application.ConsultaItinerario;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pontocerto.Application.CadastroItinerario.CadastroItinerarioUI;
import pontocerto.Application.DefaultCode.DefaultCode;
import pontocerto.Business.Admin.CadastroItinerarioValidation;
import pontocerto.Business.DTO.ConsultaRotaValidation;
import pontocerto.Common.Admin.RotasDTO;
import pontocerto.Common.DTO.FretadosDTO;
import pontocerto.Global.Enumeradores.NivelAcesso;
import pontocerto.Global.GerenciadorNivelAcesso;

/**
 *
 * @author thiag
 */
public class ConsultaItinerarioUI extends DefaultCode
{

    /**
     * Creates new form ConsultaItinerarioUI
     */
    public ConsultaItinerarioUI()
    {
        initComponents();
        validaAcessoUsuario();
        instanciaTableModel();
    }

    public ConsultaItinerarioUI(FretadosDTO fretado)
    {
        initComponents();
        validaAcessoUsuario();
        instanciaTableModel();

        idFretado = fretado.getId();
        PreencherGrid();
    }

    private int idFretado;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        painelPrincipal = new javax.swing.JPanel();
        painelMenuLateral = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblFretado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelConsultaItinerario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnVoltarConsultaFretado = new javax.swing.JButton();
        lblMensagemErroConsultaItinerario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaItinerario = new javax.swing.JTable();
        btnNovoItinerario = new javax.swing.JButton();
        btnDeletaItinerario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PONTO CERTO");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/busIcon.png")).getImage());

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setPreferredSize(new java.awt.Dimension(971, 555));

        painelMenuLateral.setBackground(new java.awt.Color(51, 102, 255));

        lblHome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/home.png"))); // NOI18N
        lblHome.setText("  Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblHomeMouseClicked(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/user.png"))); // NOI18N
        lblUsuario.setText("  Usuário");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblUsuarioMouseClicked(evt);
            }
        });

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/sair.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblSairMouseClicked(evt);
            }
        });

        lblFretado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFretado.setForeground(new java.awt.Color(255, 255, 255));
        lblFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/bus.png"))); // NOI18N
        lblFretado.setText("  Fretado");
        lblFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFretadoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PONTO");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CERTO");

        javax.swing.GroupLayout painelMenuLateralLayout = new javax.swing.GroupLayout(painelMenuLateral);
        painelMenuLateral.setLayout(painelMenuLateralLayout);
        painelMenuLateralLayout.setHorizontalGroup(
            painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMenuLateralLayout.createSequentialGroup()
                        .addComponent(lblSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFretado, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMenuLateralLayout.setVerticalGroup(
            painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLateralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        painelConsultaItinerario.setBackground(new java.awt.Color(255, 255, 255));
        painelConsultaItinerario.setPreferredSize(new java.awt.Dimension(728, 585));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consulta de Itinerário");

        btnVoltarConsultaFretado.setBackground(new java.awt.Color(51, 102, 255));
        btnVoltarConsultaFretado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVoltarConsultaFretado.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarConsultaFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/sair.png"))); // NOI18N
        btnVoltarConsultaFretado.setText("Voltar");
        btnVoltarConsultaFretado.setBorder(null);
        btnVoltarConsultaFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnVoltarConsultaFretadoMouseClicked(evt);
            }
        });

        lblMensagemErroConsultaItinerario.setBackground(new java.awt.Color(255, 255, 255));
        lblMensagemErroConsultaItinerario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMensagemErroConsultaItinerario.setEnabled(false);

        tbConsultaItinerario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Fretado", "CEP", "Rua", "Bairro", "Cidade", "Estado"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsultaItinerario);

        btnNovoItinerario.setBackground(new java.awt.Color(51, 102, 255));
        btnNovoItinerario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNovoItinerario.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/plus.png"))); // NOI18N
        btnNovoItinerario.setText("Novo");
        btnNovoItinerario.setBorder(null);
        btnNovoItinerario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNovoItinerarioMouseClicked(evt);
            }
        });

        btnDeletaItinerario.setBackground(new java.awt.Color(51, 102, 255));
        btnDeletaItinerario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDeletaItinerario.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletaItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/delete.png"))); // NOI18N
        btnDeletaItinerario.setText("Deletar");
        btnDeletaItinerario.setBorder(null);
        btnDeletaItinerario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnDeletaItinerarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaItinerarioLayout = new javax.swing.GroupLayout(painelConsultaItinerario);
        painelConsultaItinerario.setLayout(painelConsultaItinerarioLayout);
        painelConsultaItinerarioLayout.setHorizontalGroup(
            painelConsultaItinerarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                .addGroup(painelConsultaItinerarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaItinerarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(painelConsultaItinerarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagemErroConsultaItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltarConsultaFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovoItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletaItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConsultaItinerarioLayout.setVerticalGroup(
            painelConsultaItinerarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblMensagemErroConsultaItinerario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnNovoItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelConsultaItinerarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConsultaItinerarioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnDeletaItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnVoltarConsultaFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(painelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 853, Short.MAX_VALUE))
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(painelConsultaItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelConsultaItinerario, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblHomeMouseClicked
    {//GEN-HEADEREND:event_lblHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaHome();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFretadoMouseClicked
    {//GEN-HEADEREND:event_lblFretadoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaFretado();
    }//GEN-LAST:event_lblFretadoMouseClicked

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblUsuarioMouseClicked
    {//GEN-HEADEREND:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaUsuario();
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblSairMouseClicked
    {//GEN-HEADEREND:event_lblSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaLogin();
    }//GEN-LAST:event_lblSairMouseClicked

    private void btnVoltarConsultaFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnVoltarConsultaFretadoMouseClicked
    {//GEN-HEADEREND:event_btnVoltarConsultaFretadoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaFretado();
    }//GEN-LAST:event_btnVoltarConsultaFretadoMouseClicked

    private void btnNovoItinerarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnNovoItinerarioMouseClicked
    {//GEN-HEADEREND:event_btnNovoItinerarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CadastroItinerarioUI paginaCadastroItinerario = new CadastroItinerarioUI(idFretado);
        paginaCadastroItinerario.setVisible(true);
    }//GEN-LAST:event_btnNovoItinerarioMouseClicked

    private void btnDeletaItinerarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnDeletaItinerarioMouseClicked
    {//GEN-HEADEREND:event_btnDeletaItinerarioMouseClicked
        // TODO add your handling code here:
        try
        {
            if (tbConsultaItinerario.getRowCount() != 0 && tbConsultaItinerario.getSelectedRow() != -1)
            {
                String cep = model.getValueAt(tbConsultaItinerario.getSelectedRow(), 1).toString();
                
                RotasDTO rota = new RotasDTO();
                rota.getFretado().setId(idFretado);
                rota.getParada().setCEP(cep);
                
                CadastroItinerarioValidation.excluiRota(rota);

                PreencherGrid();

                MensagemAlertaErro("Usuário excluído com sucesso", false);
            }
            else
            {
                MensagemAlertaErro("Nenhum usuário selecionado", true);
            }
        }
        catch (Exception ex)
        {
            MensagemAlertaErro("Ocorreu um erro ao deletar uma rota", true);
        }
    }//GEN-LAST:event_btnDeletaItinerarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaItinerarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaItinerarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaItinerarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaItinerarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ConsultaItinerarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletaItinerario;
    private javax.swing.JButton btnNovoItinerario;
    private javax.swing.JButton btnVoltarConsultaFretado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFretado;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMensagemErroConsultaItinerario;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelConsultaItinerario;
    private javax.swing.JPanel painelMenuLateral;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTable tbConsultaItinerario;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void validaAcessoUsuario()
    {
        String nivelAcesso = GerenciadorNivelAcesso.obterInstancia().getNivelAcesso();

        if (nivelAcesso.equals(NivelAcesso.Comum.name()))
        {
            lblUsuario.setVisible(false);
            btnNovoItinerario.setVisible(false);
            btnDeletaItinerario.setVisible(false);
        }
    }

    private void instanciaTableModel()
    {
        model = (DefaultTableModel) tbConsultaItinerario.getModel();
    }

    private void PreencherGrid()
    {
        try
        {
            List<RotasDTO> listaRota = ConsultaRotaValidation.buscarRotaPorFretado(idFretado);
            model.setRowCount(0);

            if (listaRota.size() != 0)
            {
                listaRota.forEach((item) ->
                {
                    model.insertRow(model.getRowCount(), new Object[]
                    {
                        item.getFretado().getNumero(), item.getParada().getCEP(), item.getParada().getRua(), item.getParada().getBairro(), item.getParada().getCidade(), item.getParada().getEstado()
                    });
                });
            }
            else
            {
                MensagemAlertaErro("Nenhuma rota encontrada para o fretado selecionado", true);
            }
        }
        catch (Exception ex)
        {
            MensagemAlertaErro("Erro ao preencher a tabela com as rotas", true);
        }
    }

    private void MensagemAlertaErro(String mensagem, boolean erro)
    {
        Color cor = erro ? Color.red : Color.blue;

        lblMensagemErroConsultaItinerario.setVisible(true);
        lblMensagemErroConsultaItinerario.setForeground(cor);
        lblMensagemErroConsultaItinerario.setText(mensagem);
    }
}
