/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

/**
 *
 * @author thiag
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBemVindo
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ConsultarFretado = new javax.swing.JMenuItem();
        CadastrarFretado = new javax.swing.JMenuItem();
        CadastrarItinerario = new javax.swing.JMenuItem();
        ConsultarItinerario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ConsultarUsuario = new javax.swing.JMenuItem();
        CadastrarUsuario = new javax.swing.JMenuItem();
        Sobre = new javax.swing.JMenu();
        SobreDesenvolvedores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Certo");

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Fretados");

        ConsultarFretado.setText("Consultar Fretado");
        ConsultarFretado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFretadoActionPerformed(evt);
            }
        });
        jMenu1.add(ConsultarFretado);

        CadastrarFretado.setText("Cadastrar Fretado");
        CadastrarFretado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFretadoActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarFretado);

        CadastrarItinerario.setText("Cadastrar Itinerário");
        CadastrarItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarItinerarioActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarItinerario);

        ConsultarItinerario.setText("Consultar Itinerário");
        ConsultarItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarItinerarioActionPerformed(evt);
            }
        });
        jMenu1.add(ConsultarItinerario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuário");

        ConsultarUsuario.setText("Consultar");
        ConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(ConsultarUsuario);

        CadastrarUsuario.setText("Cadastrar");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(CadastrarUsuario);

        jMenuBar1.add(jMenu2);

        Sobre.setText("Sobre");

        SobreDesenvolvedores.setText("Sobre desenvolvedores");
        SobreDesenvolvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreDesenvolvedoresActionPerformed(evt);
            }
        });
        Sobre.add(SobreDesenvolvedores);

        jMenuBar1.add(Sobre);

        jMenu4.setText("Sair");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFretadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFretadoActionPerformed

        CadastroFretado telaCadastroFretado = new CadastroFretado();
        PrincipalPanel.add(telaCadastroFretado);
        telaCadastroFretado.setVisible(true);
    }//GEN-LAST:event_CadastrarFretadoActionPerformed

    private void ConsultarFretadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFretadoActionPerformed
        // TODO add your handling code here:
        ConsultaFretado telaConsultaFretado = new ConsultaFretado();
        PrincipalPanel.add(telaConsultaFretado);
        telaConsultaFretado.setVisible(true);
    }//GEN-LAST:event_ConsultarFretadoActionPerformed

    private void ConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarUsuarioActionPerformed
        // TODO add your handling code here:
        ConsultaUsuario telaConsultaUsuario = new ConsultaUsuario();
        PrincipalPanel.add(telaConsultaUsuario);
        telaConsultaUsuario.setVisible(true);
    }//GEN-LAST:event_ConsultarUsuarioActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        CadastrarUsuario telaCadastrarUsuario = new CadastrarUsuario();
        PrincipalPanel.add(telaCadastrarUsuario);
        telaCadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void SobreDesenvolvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreDesenvolvedoresActionPerformed
        // TODO add your handling code here:
        Sobre telaSobre = new Sobre();
        PrincipalPanel.add(telaSobre);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_SobreDesenvolvedoresActionPerformed

    private void CadastrarItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarItinerarioActionPerformed
        // TODO add your handling code here:
        CadastroItinerario telaCadastroItinerario = new CadastroItinerario();
        PrincipalPanel.add(telaCadastroItinerario);
        telaCadastroItinerario.setVisible(true);
    }//GEN-LAST:event_CadastrarItinerarioActionPerformed

    private void ConsultarItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarItinerarioActionPerformed
        // TODO add your handling code here:
        ConsultaItinerario telaConsultaItinerario = new ConsultaItinerario();
        PrincipalPanel.add(telaConsultaItinerario);
        telaConsultaItinerario.setVisible(true);
    }//GEN-LAST:event_ConsultarItinerarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarFretado;
    private javax.swing.JMenuItem CadastrarItinerario;
    private javax.swing.JMenuItem CadastrarUsuario;
    private javax.swing.JMenuItem ConsultarFretado;
    private javax.swing.JMenuItem ConsultarItinerario;
    private javax.swing.JMenuItem ConsultarUsuario;
    private javax.swing.JDesktopPane PrincipalPanel;
    private javax.swing.JMenu Sobre;
    private javax.swing.JMenuItem SobreDesenvolvedores;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
