/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pontocerto.Application.ConsultaFretado;

import java.awt.Color;
import java.time.LocalTime;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pontocerto.Application.AlteraFretado.AlteraFretadoUI;
import pontocerto.Application.CadastroFretado.CadastroFretadoUI;
import pontocerto.Application.ConsultaItinerario.ConsultaItinerarioUI;
import pontocerto.Application.DefaultCode.DefaultCode;
import pontocerto.Business.DTO.ConsultaFretadoValidation;
import pontocerto.Common.DTO.FretadosDTO;
import pontocerto.Global.Enumeradores.NivelAcesso;
import pontocerto.Global.GerenciadorNivelAcesso;

/**
 *
 * @author thiag
 */
public class ConsultaFretadoUI extends DefaultCode
{

    DefaultTableModel model;

    /**
     * Creates new form ConsultaFretadoUI
     */
    public ConsultaFretadoUI()
    {
        initComponents();
        validaAcessoUsuario();
        instanciaTableModel();
        tbConsultaFretado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        painelPrincipal = new javax.swing.JPanel();
        painelMenuLateral = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblFretado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelConsultaFretado = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblMensagemErroConsultaUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaFretado = new javax.swing.JTable();
        btnNovoFretado = new javax.swing.JButton();
        btnDeletarFretado = new javax.swing.JButton();
        btnConsultarRota = new javax.swing.JButton();
        btnAlterarFretado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PONTO CERTO");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/busIcon.png")).getImage());

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        painelMenuLateral.setBackground(new java.awt.Color(51, 102, 255));

        lblHome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/home.png"))); // NOI18N
        lblHome.setText("  Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblHomeMouseClicked(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/user.png"))); // NOI18N
        lblUsuario.setText("  Usuário");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblUsuarioMouseClicked(evt);
            }
        });

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/sair.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblSairMouseClicked(evt);
            }
        });

        lblFretado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFretado.setForeground(new java.awt.Color(255, 255, 255));
        lblFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/bus.png"))); // NOI18N
        lblFretado.setText("  Fretado");
        lblFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFretadoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PONTO");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CERTO");

        javax.swing.GroupLayout painelMenuLateralLayout = new javax.swing.GroupLayout(painelMenuLateral);
        painelMenuLateral.setLayout(painelMenuLateralLayout);
        painelMenuLateralLayout.setHorizontalGroup(
            painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMenuLateralLayout.createSequentialGroup()
                        .addComponent(lblSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFretado, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMenuLateralLayout.setVerticalGroup(
            painelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLateralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        painelConsultaFretado.setBackground(new java.awt.Color(255, 255, 255));
        painelConsultaFretado.setPreferredSize(new java.awt.Dimension(728, 585));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consulta de Fretados");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CEP");

        txtCep.setBackground(new java.awt.Color(255, 255, 255));
        txtCep.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCep.setForeground(new java.awt.Color(0, 0, 0));
        txtCep.setToolTipText("Digite o número do fretado");
        txtCep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Rua");

        txtRua.setBackground(new java.awt.Color(255, 255, 255));
        txtRua.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRua.setForeground(new java.awt.Color(0, 0, 0));
        txtRua.setToolTipText("Digite a descrição do fretado");
        txtRua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisar.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(null);
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnPesquisarMouseClicked(evt);
            }
        });

        lblMensagemErroConsultaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblMensagemErroConsultaUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        tbConsultaFretado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Numero", "Descricao", "Entrada", "Saida"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsultaFretado);

        btnNovoFretado.setBackground(new java.awt.Color(51, 102, 255));
        btnNovoFretado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNovoFretado.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/plus.png"))); // NOI18N
        btnNovoFretado.setText("Novo");
        btnNovoFretado.setBorder(null);
        btnNovoFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNovoFretadoMouseClicked(evt);
            }
        });

        btnDeletarFretado.setBackground(new java.awt.Color(51, 102, 255));
        btnDeletarFretado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDeletarFretado.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletarFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/delete.png"))); // NOI18N
        btnDeletarFretado.setText("Deletar");
        btnDeletarFretado.setBorder(null);
        btnDeletarFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnDeletarFretadoMouseClicked(evt);
            }
        });

        btnConsultarRota.setBackground(new java.awt.Color(51, 102, 255));
        btnConsultarRota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConsultarRota.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarRota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/plus.png"))); // NOI18N
        btnConsultarRota.setText("Rota");
        btnConsultarRota.setBorder(null);
        btnConsultarRota.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnConsultarRotaMouseClicked(evt);
            }
        });

        btnAlterarFretado.setBackground(new java.awt.Color(51, 102, 255));
        btnAlterarFretado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAlterarFretado.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarFretado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocerto/Images/update.png"))); // NOI18N
        btnAlterarFretado.setText("Alterar");
        btnAlterarFretado.setBorder(null);
        btnAlterarFretado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAlterarFretadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaFretadoLayout = new javax.swing.GroupLayout(painelConsultaFretado);
        painelConsultaFretado.setLayout(painelConsultaFretadoLayout);
        painelConsultaFretadoLayout.setHorizontalGroup(
            painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaFretadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMensagemErroConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNovoFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletarFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarRota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConsultaFretadoLayout.setVerticalGroup(
            painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblMensagemErroConsultaUsuario)
                .addGap(33, 33, 33)
                .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelConsultaFretadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultaFretadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaFretadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnConsultarRota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletarFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(painelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 853, Short.MAX_VALUE))
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(painelConsultaFretado, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelConsultaFretado, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblHomeMouseClicked
    {//GEN-HEADEREND:event_lblHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaHome();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFretadoMouseClicked
    {//GEN-HEADEREND:event_lblFretadoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaFretado();
    }//GEN-LAST:event_lblFretadoMouseClicked

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblUsuarioMouseClicked
    {//GEN-HEADEREND:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaUsuario();
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblSairMouseClicked
    {//GEN-HEADEREND:event_lblSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
        abrirPaginaLogin();
    }//GEN-LAST:event_lblSairMouseClicked

    private void btnNovoFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnNovoFretadoMouseClicked
    {//GEN-HEADEREND:event_btnNovoFretadoMouseClicked
        // TODO add your handling code here:
        this.dispose();

        CadastroFretadoUI paginaCadastroFretado = new CadastroFretadoUI();
        paginaCadastroFretado.setVisible(true);
    }//GEN-LAST:event_btnNovoFretadoMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPesquisarMouseClicked
    {//GEN-HEADEREND:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        lblMensagemErroConsultaUsuario.setVisible(false);

        try
        {
            String cep = txtCep.getText().trim();
            String rua = txtRua.getText().trim();

            if (!cep.equals(""))
            {
                Integer.parseInt(cep);
            }

            boolean validacao = ConsultaFretadoValidation.validaCampos(cep, rua);

            if (validacao)
            {
                MensagemAlertaErro("Informe apenas o CEP ou a Rua a qual deseja fazer a pesquisa", true);
            }
            else
            {
                List<FretadosDTO> listaFretados = getListaFretados(cep, rua);

                PreencheGrid(listaFretados);
            }
        }
        catch (NumberFormatException ex)
        {
            MensagemAlertaErro("O campo CEP deve conter apenas números", true);
        }
        catch (Exception ex)
        {
            MensagemAlertaErro("Ocorreu um erro ao obter a lista de fretado", true);
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private List<FretadosDTO> getListaFretados(String cep, String rua)
    {
        List<FretadosDTO> listaFretados = null;
        if (cep.equals("") && rua.equals(""))
        {
            listaFretados = ConsultaFretadoValidation.listaFretados();
        }
        else
        {
            listaFretados = ConsultaFretadoValidation.pesquisaFretado(cep, rua);
        }
        if (listaFretados == null || listaFretados.size() == 0)
        {
            MensagemAlertaErro("Nenhum fretado encontrado para o CEP ou Rua informados", true);
        }
        return listaFretados;
    }

    private void btnDeletarFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnDeletarFretadoMouseClicked
    {//GEN-HEADEREND:event_btnDeletarFretadoMouseClicked
        // TODO add your handling code here:
        try
        {
            if (tbConsultaFretado.getRowCount() != 0 && tbConsultaFretado.getSelectedRow() != -1)
            {
                FretadosDTO fretado = getFretadoSelecionado();

                fretado = ConsultaFretadoValidation.buscaFretadoPorNumeroHorario(fretado);
                ConsultaFretadoValidation.deletaFretado(fretado);

                String cep = txtCep.getText().trim();
                String rua = txtRua.getText().trim();

                if (!cep.equals(""))
                {
                    Integer.parseInt(cep);
                }

                boolean validacao = ConsultaFretadoValidation.validaCampos(cep, rua);

                if (validacao)
                {
                    MensagemAlertaErro("Informe apenas o CEP ou a Rua a qual deseja fazer a pesquisa", true);
                }
                else
                {
                    List<FretadosDTO> listaFretados = getListaFretados(cep, rua);

                    PreencheGrid(listaFretados);
                }
            }
            else
            {
                MensagemAlertaErro("Nenhum fretado selecionado", true);
            }
        }
        catch (Exception ex)
        {
            MensagemAlertaErro("Ocorreu um erro ao deletar o fretado", true);
        }
    }//GEN-LAST:event_btnDeletarFretadoMouseClicked

    private FretadosDTO getFretadoSelecionado() throws NumberFormatException
    {
        int numeroFretado = Integer.parseInt(model.getValueAt(tbConsultaFretado.getSelectedRow(), 0).toString());
        String descricao = model.getValueAt(tbConsultaFretado.getSelectedRow(), 1).toString();
        LocalTime entrada = LocalTime.parse(model.getValueAt(tbConsultaFretado.getSelectedRow(), 2).toString());
        LocalTime saida = LocalTime.parse(model.getValueAt(tbConsultaFretado.getSelectedRow(), 3).toString());

        FretadosDTO fretado = new FretadosDTO();
        fretado.setNumero(numeroFretado);
        fretado.setDescricao(descricao);
        fretado.setEntrada(entrada);
        fretado.setSaida(saida);

        fretado = ConsultaFretadoValidation.buscaFretadoPorNumeroHorario(fretado);

        return fretado;
    }

    private void btnConsultarRotaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnConsultarRotaMouseClicked
    {//GEN-HEADEREND:event_btnConsultarRotaMouseClicked
        // TODO add your handling code here:
        if (tbConsultaFretado.getRowCount() != 0 && tbConsultaFretado.getSelectedRow() != -1)
        {
            this.dispose();
            FretadosDTO fretado = getFretadoSelecionado();
            ConsultaItinerarioUI paginaConsultaItinerario = new ConsultaItinerarioUI(fretado);
            paginaConsultaItinerario.setVisible(true);
        }
        else
        {
            MensagemAlertaErro("Nenhum fretado selecionado", true);
        }
    }//GEN-LAST:event_btnConsultarRotaMouseClicked

    private void btnAlterarFretadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAlterarFretadoMouseClicked
    {//GEN-HEADEREND:event_btnAlterarFretadoMouseClicked
        // TODO add your handling code here:
        if (tbConsultaFretado.getRowCount() != 0 && tbConsultaFretado.getSelectedRow() != -1)
        {
            this.dispose();

            FretadosDTO fretado = getFretadoSelecionado();

            AlteraFretadoUI paginaAlteraFretado = new AlteraFretadoUI(fretado);
            paginaAlteraFretado.setVisible(true);
        }
        else
        {
            MensagemAlertaErro("Nenhum fretado selecionado", true);
        }
    }//GEN-LAST:event_btnAlterarFretadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaFretadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaFretadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaFretadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ConsultaFretadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ConsultaFretadoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFretado;
    private javax.swing.JButton btnConsultarRota;
    private javax.swing.JButton btnDeletarFretado;
    private javax.swing.JButton btnNovoFretado;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFretado;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMensagemErroConsultaUsuario;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelConsultaFretado;
    private javax.swing.JPanel painelMenuLateral;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTable tbConsultaFretado;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void validaAcessoUsuario()
    {
        String nivelAcesso = GerenciadorNivelAcesso.obterInstancia().getNivelAcesso();

        if (nivelAcesso.equals(NivelAcesso.Comum.name()))
        {
            lblUsuario.setVisible(false);
            btnNovoFretado.setVisible(false);
            btnAlterarFretado.setVisible(false);
            btnDeletarFretado.setVisible(false);
        }
    }

    private void instanciaTableModel()
    {
        model = (DefaultTableModel) tbConsultaFretado.getModel();
    }

    private void MensagemAlertaErro(String mensagem, boolean erro)
    {
        Color cor = erro ? Color.red : Color.blue;

        lblMensagemErroConsultaUsuario.setVisible(true);
        lblMensagemErroConsultaUsuario.setForeground(cor);
        lblMensagemErroConsultaUsuario.setText(mensagem);

    }

    private void PreencheGrid(List<FretadosDTO> listaFretados)
    {
        tbConsultaFretado.setVisible(true);

        model.setRowCount(0);

        listaFretados.forEach((item) ->
        {
            model.insertRow(model.getRowCount(), new Object[]
            {
                item.getNumero(), item.getDescricao(), item.getEntrada(), item.getSaida()
            });
        });
    }
}
